### NumPy

#### Numerical Python 행렬 연산이나 다차원 배열을 편리하게 처리

#### 행렬 합 구하기

In [3]:
matrix_1 = [[1,2], [3,4]]
matrix_2 = [[5,6], [7,8]]

matrix_result = []
for i in range(len(matrix_1)):
    tmp = []
    for j in range(len(matrix_2)):
        tmp.append(matrix_1[i][j] + matrix_2[i][j])
    matrix_result.append(tmp)
    
print(matrix_result)

[[6, 8], [10, 12]]


In [4]:
import numpy as np

matrix_result = np.array(matrix_1) + np.array(matrix_2)
print(matrix_result)

[[ 6  8]
 [10 12]]


#### matrix_1에 숫자 1씩 더하기

In [9]:
matrix_1 = [[1,2], [3,4]]

for i in range(len(matrix_1)):
    for j in range(len(matrix_1)):
        matrix_1[i][j] = matrix_1[i][j] + 1
    
print(matrix_1)

[[2, 3], [4, 5]]


In [10]:
matrix_1 = [[1,2], [3,4]]

matrix_1 = np.array(matrix_1) + 1
print(matrix_1)

[[2 3]
 [4 5]]


In [16]:
matrix_1 = [['aa', 'bb'], [3.4, 1]]

np.array(matrix_1)

array([['aa', 'bb'],
       ['3.4', '1']], dtype='<U3')

### 속도비교

In [15]:
import time

size = 10000000

#list
x = list(range(size))
y = list(range(size))

start_time = time.time()
z = [x[i]+x[i] for i in range(size)]
#z
print('리스트 걸린 시간', time.time() - start_time)

# adlist
x = np.array(size)
y = np.array(size)
start_time = time.time()
z = x + y
print('넘파이 걸린 시간', time.time() - start_time)

리스트 걸린 시간 1.6049914360046387
넘파이 걸린 시간 0.1997678279876709


### ndarray

In [18]:
x = np.uint(32)
print(x)
print(x.dtype)

32
uint64


In [19]:
x = np.array([1, 2, 3, 4])
print(x)
print(x.dtype)

[1 2 3 4]
int64


In [20]:
x = np.float32([1, 2, 3, 4])
print(x)
print(x.dtype)

[1. 2. 3. 4.]
float32


In [22]:
x = np.array([1, 2, 3, 4], dtype = np.float32)
print(x)
print(x.dtype)

x = np.int32(x)
print(x)
print(x.dtype)
np.issubdtype(x.dtype, np.int32)

[1. 2. 3. 4.]
float32
[1 2 3 4]
int32


True

### 다차원 ndarray

In [23]:
x = np.array(1)
print(x.shape) # 행렬구조
print(x.ndim) # 몇차원인지
print(x.size) # 개수

()
0
1


In [24]:
x = np.array([1,2])
print(x.shape)
print(x.ndim)
print(x.size)

(2,)
1
2


In [26]:
x = np.array([[1,2,3], [4,5,6]]) # ([[]])
print(x.shape)
print(x.ndim)
print(x.size)

(2, 3)
2
6


### arange
#### 파이썬의 range와 비슷

In [32]:
x = np.arange(10)
print(x)
x = np.arange(10.0)
print(x)
x = np.arange(1,10,2)
print(x)
x = np.arange(1,10,0.5)
print(x)
x = np.arange(10,1,-0.5)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[1 3 5 7 9]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5  2.   1.5]


### linspace
#### 균일한 간격으로 리스트 크기만큼의 리스트 생성
#### np.linspace(시작값, 끝값, 벡터크기)
#### 끝값 포함 여부 np.linspace(시작값, 끝값, 벡터크기, endpoint = False)

In [33]:
x = np.linspace(1,20,5)
print(x)

[ 1.    5.75 10.5  15.25 20.  ]


In [35]:
x = np.linspace(1,20,10, endpoint = False)
print(x)

[ 1.   2.9  4.8  6.7  8.6 10.5 12.4 14.3 16.2 18.1]


### reshape
#### 데이터를 유지하면서 차원의 형태를 변경

In [36]:
x = np.arange(9).reshape(3,3) # 2차원
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [37]:
x = np.arange(24).reshape(2,3,4) # 3차원
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [38]:
x = np.arange(16).reshape(2,2,2,2) # 4차원
print(x)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [40]:
x = np.array([[1,2],[3,4],[5,6]]).reshape(2,3)
# 데이터를 유지하고 형태변경
print(x)

[[1 2 3]
 [4 5 6]]


In [41]:
x = np.arange(9).reshape(3,-1)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
